language: 
  node_js
node_js:
  - "7"
sudo: required
dist: trusty
addons:
    chrome: stable
before_install:
  - npm i -g npm@5.8.0
before_script:
    - "sudo chown root /opt/google/chrome/chrome-sandbox"
    - "sudo chmod 4755 /opt/google/chrome/chrome-sandbox"
    - "export CHROME_BIN=google-chrome"
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in travis-ci.org dashboard, marked secure
  keep-history: true
  on:
    branch: master
  local-dir: "src"